version: "3.2"
services:
  apache:
    build:
      context: '.'
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "${DB_PORT}:${DB_PORT}/tcp"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    networks:
      - backend
    volumes:
      - /var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
networks:
  frontend:
  backend:
volumes:
  data:
